### PR TITLE
Could you open issues for bug reports?

### PR DESCRIPTION
**Pull request by rugk**
Hi and sorry, I need to use this way to get in contact with you @k4zmu2a as there is an issue with your code.

It's an awesome project, but having the controls in the Readme would be nice, see https://github.com/k4zmu2a/SpaceCadetPinball/issues/44.

Also why not open the issue tracker here, so we can report bugs in a better way?

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Might as well post this here, then.

You cannot enable/disable sound or music on your fork---but hey, having a playable github.io is great!

**Comment by isiah-lloyd** [comment]
Does anyone know how to build this project? I'm able to build the desktop app but not sure how to build the emscripten port

**Comment by Draco18s** [comment]
origin/master issue 25's fix needs to be pulled
https://github.com/k4zmu2a/SpaceCadetPinball/issues/25

**Comment by markusbkk** [comment]
> Does anyone know how to build this project? I'm able to build the desktop app but not sure how to build the emscripten port

I struggled for a bit, as well. Initially thought I could/should just set `CMAKE_SYSTEM_NAME=emscripten` and it would work.
You need to actually use the Emscripten specific wrapper tools.

[I created a fork of the project with updated instructions](https://github.com/markusbkk/SpaceCadetPinball-WASM) (had to clone locally and create a hard fork, because I already forked the PPC port through the GitHub UI).

Will be happy to accept PRs and Bug Reports

**Comment by 1j01** [comment]
For anyone who's interested, I found [a way to toggle audio](https://github.com/1j01/98/blob/cdcc4ddc2ba2cbdad223811352aebc12e4a08b28/programs/pinball/space-cadet.html#L129-L140), although not separately music and sound, and a hacky way of implementing custom (Windows 98 themed) menus, by [triggering clicks on the ImGui menus](https://github.com/1j01/98/blob/cdcc4ddc2ba2cbdad223811352aebc12e4a08b28/programs/pinball/space-cadet-menus.js#L212-L232) and [hiding the ImGui menus with an absolutely positioned image](https://github.com/1j01/98/blob/cdcc4ddc2ba2cbdad223811352aebc12e4a08b28/programs/pinball/space-cadet.html#L105), a cropped screenshot. (This technique only works because the game's UI is static in that area!) You can see it in action on my web desktop [98.js.org](https://98.js.org/).
It'd be nice to get those few last features working, but overall I'm very satisfied with this project!

**Comment by markusbkk** [comment]
> For anyone who's interested, I found [a way to toggle audio](https://github.com/1j01/98/blob/cdcc4ddc2ba2cbdad223811352aebc12e4a08b28/programs/pinball/space-cadet.html#L129-L140), although not separately music and sound, and a hacky way of implementing custom (Windows 98 themed) menus, by [triggering clicks on the ImGui menus](https://github.com/1j01/98/blob/cdcc4ddc2ba2cbdad223811352aebc12e4a08b28/programs/pinball/space-cadet-menus.js#L212-L232) and [hiding the ImGui menus with an absolutely positioned image](https://github.com/1j01/98/blob/cdcc4ddc2ba2cbdad223811352aebc12e4a08b28/programs/pinball/space-cadet.html#L105), a cropped screenshot. (This technique only works because the game's UI is static in that area!) You can see it in action on my web desktop [98.js.org](https://98.js.org/). It'd be nice to get those few last features working, but overall I'm very satisfied with this project!

ImGUI is fully stylable. I believe there might even exist a Win32 style already. If not, we could work on one.
Haven't worked on my fork in a while (I'm trying to completely rebase it with new changes not in this fork) but I can look into styling.

As for toggling music, that's a bug from the MIDI implementation used in this fork. For my fork, I considered going with mp3/ogg since I've not been able to fix the MIDI bug from this fork, thus far and since I'd prefer a modernized fork with just some "classic" features in a separate branch.

EDIT: Here's a fork of IMGUI that implements Windows 98 styling.

https://github.com/JakeCoxon/imgui-win98

**Comment by alula** [comment]
Sorry for late response, I didn't get any emails from this repo for some reason.
Issues are open!

**Comment by alula** [comment]
I guess I can close this PR since merging that branch doesn't make sense and I suppose it was just a way to communicate :)

**Pull request closed without merging**
